const IdTakenError = require('../../src/common/id-taken-error.js');
const validateRequiredArg = require('oprr-utilities').validateRequiredArg;
const OprViewConfiguration = require('./opr-view-configuration.js');

/**
 * Represents the current OPR Project
 */
class OprProject {
    constructor() {
        const _self = this;
        /**
                * @typedef {Object} ContentComponentInstanceEnvelope
                * @property {string} typeId
                * @property {string} instanceName the name given to the instance
                * @property {Object} instance the content component instance
                */

        /** @type {Object<string, ContentComponentInstanceEnvelope} */
        const _contentComponentInstanceIdToInstanceEnvelopeMap = new Map();

        const _currentOprViewConfig = new OprViewConfiguration();

        /**
         * 
         * @param {Object} contentComponentInstance the instance of the contentComponent to be added to the project.
         * @param {string} contentComponentTypeId the content component id like provided by its respective meta data.
         * @param {string} contentComponentInstanceName unique name under which the Content Component will be identified by the system and the user, can be specified by the user.
         * @returns {string} the content component id used for this instance within this opr project
         */
        this.addContentComponent = function (contentComponentInstance, contentComponentTypeId, contentComponentInstanceName) {
            validateRequiredArg(contentComponentInstance, 'content component instance required');
            validateRequiredArg(contentComponentTypeId, 'content component type id required');
            validateRequiredArg(contentComponentInstanceName, 'name required');
            const contentComponentInstanceId = contentComponentInstanceName;//use name as id

            if (_contentComponentInstanceIdToInstanceEnvelopeMap.has(contentComponentInstanceId))
                throw new IdTakenError(`${contentComponentInstanceId} already in use`);
            _contentComponentInstanceIdToInstanceEnvelopeMap.set(contentComponentInstanceId, _makeContentComponentInstanceEnvelope(contentComponentInstance, contentComponentInstanceName, contentComponentTypeId));

            // console.log(`adding ccInst of type ${contentComponentTypeId} with id ${contentComponentInstanceName} `);

            return contentComponentInstanceId;
        }

        /**
         * 
         * @param {Object} contentComponentInstance 
         * @param {string} contentComponentInstanceName 
         * @param {string} contentComponentTypeId 
         * @returns {ContentComponentInstanceEnvelope}
         */
        function _makeContentComponentInstanceEnvelope(contentComponentInstance, contentComponentInstanceName, contentComponentTypeId) {
            return {
                typeId: contentComponentTypeId,
                instanceName: contentComponentInstanceName,
                instance: contentComponentInstance
            };
        }

        /**
         * 
         * @param {string} contentComponentInstanceId the instance id, provided when the component instance was added (not the conten component type id).
         * @returns the instance of the content component
         */
        this.getContentComponent = function (contentComponentInstanceId) {
            if (_contentComponentInstanceIdToInstanceEnvelopeMap.has(contentComponentInstanceId))
                return _contentComponentInstanceIdToInstanceEnvelopeMap.get(contentComponentInstanceId).instance;
        }

        /**
         * 
         * @param {string} contentComponentTypeId the content component id like provided by its respective meta data.
         */
        this.getContentComponentTypeCount = function (contentComponentTypeId) {
            let typeCount = 0;

            _contentComponentInstanceIdToInstanceEnvelopeMap.forEach((value) => { if (contentComponentTypeId === value.typeId) typeCount++; });

            return typeCount;
        }

        /**
         * @typedef {Object} ContentComponentInstanceMetadata
         * @property {string} contentComponentInstanceId generated by opr project when new content component is added
         * @property {string} contentComponentInstanceName specified by user when new instance is added
         * @property {string} contentComponentTypeId stored in opr project but provided from content component itself
         */

        /**
         * @returns {ContentComponentInstanceMetadata[]}
         */
        this.getAddedContentComponentInstancesList = function () {
            let result = [];
            _contentComponentInstanceIdToInstanceEnvelopeMap.forEach(
                (envelope, contentComponentInstanceId) =>
                    result.push({
                        contentComponentInstanceId: contentComponentInstanceId,
                        contentComponentInstanceName: envelope.instanceName,
                        contentComponentTypeId: envelope.typeId
                    })
            );
            return result;
        }

        /**
         * 
         * @param {string} contentComponentInstanceId 
         * @param {string} contentViewTypeId 
         * @returns {string} viewId the id of the view within the content component
         */
        this.addContentComponentView = function (contentComponentInstanceId, contentViewTypeId) {
            if (!_contentComponentInstanceIdToInstanceEnvelopeMap.has(contentComponentInstanceId))
                throw new Error(`${contentComponentInstanceId} is an unknown Content Component Instance`);

            /** @type {ContentComponentInstanceEnvelope} */
            const addressedContentComponentInstance = _contentComponentInstanceIdToInstanceEnvelopeMap.get(contentComponentInstanceId);
            const assignedViewId = addressedContentComponentInstance.instance.addDomBasedView(contentViewTypeId);

            return assignedViewId;
        }

        this.getContentViewTypeId = function (contentComponentInstanceId, contentViewId) {
            if (!_contentComponentInstanceIdToInstanceEnvelopeMap.has(contentComponentInstanceId))
                throw new Error(`${contentComponentInstanceId} is an unknown Content Component Instance`);
            return _contentComponentInstanceIdToInstanceEnvelopeMap.get(contentComponentInstanceId).getDomBasedViewTypeId(contentViewId);
        }

        /**
         * @typedef {Object} ContentViewMetadata
         * @property {string} contentViewId generated by content component instance and stored in opr view
         * @property {string} contentViewName specified by user and stored in opr view
         * @property {string} contentViewTypeId  retrieved from content component instance       
         * @property {ContentComponentInstanceMetadata} contentComponentInstanceMetadata the content component metadata the conten view is related to
         */

        /**
         * @returns {ContentViewMetadata[]}
         */
        this.getContentViewMetadataInCurrentOprView = function () {

            const oprViewContentViewMetadataList = _currentOprViewConfig.getContentViewMetadataList()
            let resultList = [];
            for (let i = 0; i < oprViewContentViewMetadataList.length; i++) {
                const metadata = oprViewContentViewMetadataList[i];
                /** @type {ContentComponentInstanceEnvelope} */
                const contentComponentInstanceEnvelope = _contentComponentInstanceIdToInstanceEnvelopeMap.get(metadata.ccInstId);
                resultList.push(
                    {
                        contentViewId: metadata.ccInstContentViewId,
                        contentViewName: metadata.oprViewContentViewName,
                        contentViewTypeId: contentComponentInstanceEnvelope.instance.getDomBasedViewTypeId(metadata.ccInstContentViewId),
                        contentComponentInstanceMetadata: {
                            contentComponentInstanceId: metadata.ccInstId,
                            contentComponentInstanceName: contentComponentInstanceEnvelope.instanceName,
                            contentComponentTypeId: contentComponentInstanceEnvelope.typeId
                        }
                    }
                )
            }
            return resultList;
        }

        this.getCurrentOprViewConfigVerticalGridLineList = function () {
            return _currentOprViewConfig.getLayoutGrid().getVerticalGridLineList();
        }

        this.getCurrentOprViewConfigHorizontalGridLineList = function () {
            return _currentOprViewConfig.getLayoutGrid().getHorizontalGridLineList();
        }

        this.getCurrentOprViewConfigContentViewsWithBoundaryList = function () {
            return _currentOprViewConfig.getContentViewsWithBoundaryList();
        }

        this.getCurrentOprViewConfigurationContentViewNamesList = function () {
            return _currentOprViewConfig.getContentViewNamesList();
        }

        this.setCurrentOprViewConfigurationVerticalGridLineFromLeft = function (lineName, offset) {
            _currentOprViewConfig.getLayoutGrid().setVerticalGridLineFromLeft(lineName, offset);
        }
        this.setCurrentOprViewConfigurationHorizontalGridLineFromTop = function (lineName, offset) {
            _currentOprViewConfig.getLayoutGrid().setHorizontalGridLineFromTop(lineName, offset);
        }

        this.getCurrentOprViewConfigContentViewBoundary = function (viewName) {
            return _currentOprViewConfig.getContentViewBoundaryNames(viewName);
        }
        /**
          * @typedef {Object} GridLineNames
          * @property {string} left
          * @property {string} right
          * @property {string} top
          * @property {string} bottom
          */
        /**
         * 
         * @param {string} viewName 
         * @param {GridLineNames} lineNames 
         */
        this.setCurrentOprViewConfigContentViewBoundary = function (viewName, lineNames) {
            _currentOprViewConfig.setContentViewBoundary(viewName, lineNames);
        }

        this.getCurrentOprViewConfigVerticalGridLineLeftOffset = function(gridLineName) {
            return _currentOprViewConfig.getLayoutGrid().getVerticalGridLineLeftOffset(gridLineName);
        }

        this.getCurrentOprViewConfigHorizontalGridLineTopOffset = function(gridLineName) {
            return _currentOprViewConfig.getLayoutGrid().getHorizontalGridLineTopOffset(gridLineName);
        }
  /**
         * 
         * @param {string} contentViewName 
         * @param {string} contentComponentName 
         * @param {string} contentViewId 
         */
        this.addContentViewToCurrentOprViewConfig = function(contentViewName, contentComponentInstanceId, contentViewId) {
            _currentOprViewConfig.addContentView(contentViewName, contentComponentInstanceId, contentViewId)
        }
    }
}
module.exports = OprProject;
